name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build
      uses: actions/setup-node@v1
      with: 
        node-version: '14'
      
    - name: npm install and build
      run: |
              npm install
              npm run build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACCESS_TOKEN.ACCESS_TOKEN }}
        publish_dir: ./dist
        
